openapi: 3.0.0
info:
  title: AIDO Authentication API
  version: 1.0.0
  description: API for user authentication in the AIDO todo application

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - first_name
                - last_name
                - email
                - password
                - confirm_password
              properties:
                first_name:
                  type: string
                  example: "John"
                last_name:
                  type: string
                  example: "Doe"
                email:
                  type: string
                  format: email
                  example: "john.doe@example.com"
                password:
                  type: string
                  format: password
                  example: "securePassword123"
                confirm_password:
                  type: string
                  format: password
                  example: "securePassword123"
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  email:
                    type: string
                    format: email
                  first_name:
                    type: string
                  last_name:
                    type: string
        '400':
          description: Invalid input or passwords do not match

  /auth/login:
    post:
      summary: Sign in user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                    example: "bearer"
        '401':
          description: Invalid credentials

  /auth/forgot-password:
    post:
      summary: Request password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: Password reset instructions sent
        '404':
          description: User not found

  /auth/reset-password:
    post:
      summary: Reset password with token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - new_password
                - confirm_new_password
              properties:
                token:
                  type: string
                new_password:
                  type: string
                confirm_new_password:
                  type: string
      responses:
        '200':
          description: Password reset successful
        '400':
          description: Invalid token or passwords do not match
        '404':
          description: Token not found or expired